export const data = JSON.parse("{\"key\":\"v-8d550dcc\",\"path\":\"/java-core/session7.html\",\"title\":\"Bài 7. Phương thức\",\"lang\":\"en-US\",\"frontmatter\":{},\"excerpt\":\"<!-- ---\\nlayout: Post\\ntitle: Bài 7. Phương thức trong Java\\nsubtitle: Lập trình Java căn bản\\nauthor: Theanishtar\\ndate: 2023-06-08\\nuseHeaderImage: false\\nheaderImage: https://github.com/dangtranhuu/images/blob/main/angurvad/java-core/session7/banner.png?raw=true\\nheaderMask: rgba(30, 69, 110, 0.61)\\npermalinkPattern: /ebook/java/java-core/:slug/\\ntags:\\n  - Java Core\\n---\\n\\nPhương thức là cấu trúc chương trình thú vị do chính bản thân ta có thể xây dựng được. Cùng mình tìm hiểu về **Phương thức** nhé!! -->\\n\",\"headers\":[{\"level\":2,\"title\":\"1. Khái niệm\",\"slug\":\"_1-khai-niem\",\"children\":[]},{\"level\":2,\"title\":\"2. Khai báo\",\"slug\":\"_2-khai-bao\",\"children\":[{\"level\":3,\"title\":\"Phương thức không có dữ liệu trả về\",\"slug\":\"phuong-thuc-khong-co-du-lieu-tra-ve\",\"children\":[]},{\"level\":3,\"title\":\"Phương thức có dữ liệu trả về\",\"slug\":\"phuong-thuc-co-du-lieu-tra-ve\",\"children\":[]}]},{\"level\":2,\"title\":\"3. Tham số và đối số trong phương thức\",\"slug\":\"_3-tham-so-va-đoi-so-trong-phuong-thuc\",\"children\":[{\"level\":3,\"title\":\"Tham số\",\"slug\":\"tham-so\",\"children\":[]},{\"level\":3,\"title\":\"Đối số\",\"slug\":\"đoi-so\",\"children\":[]}]},{\"level\":2,\"title\":\"4. Giá trị trả về\",\"slug\":\"_4-gia-tri-tra-ve\",\"children\":[]},{\"level\":2,\"title\":\"5. Phạm vi của biến\",\"slug\":\"_5-pham-vi-cua-bien\",\"children\":[]},{\"level\":2,\"title\":\"6. Hàm đệ quy\",\"slug\":\"_6-ham-đe-quy\",\"children\":[{\"level\":3,\"title\":\"Thành phần trong hàm đệ quy gồm những gì?\",\"slug\":\"thanh-phan-trong-ham-đe-quy-gom-nhung-gi\",\"children\":[]},{\"level\":3,\"title\":\"Các ưu điểm, hạn chế và điều kiện để thực hiện đệ quy\",\"slug\":\"cac-uu-điem-han-che-va-đieu-kien-đe-thuc-hien-đe-quy\",\"children\":[{\"level\":4,\"title\":\"Ưu điểm của đệ quy\",\"slug\":\"uu-điem-cua-đe-quy\",\"children\":[]},{\"level\":4,\"title\":\"Về nhược điểm của đệ quy\",\"slug\":\"ve-nhuoc-điem-cua-đe-quy\",\"children\":[]}]},{\"level\":3,\"title\":\"Để viết được đệ quy cần đảm bảo yếu tố gì?\",\"slug\":\"đe-viet-đuoc-đe-quy-can-đam-bao-yeu-to-gi\",\"children\":[]},{\"level\":3,\"title\":\"Ứng dụng cụ thể của Đệ quy\",\"slug\":\"ung-dung-cu-the-cua-đe-quy\",\"children\":[]}]}],\"readingTime\":{\"minutes\":12,\"words\":1794},\"filePathRelative\":\"java-core/session7.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
