export const pagesRoutes = [
  ["v-31767f5b","/about/project.html",{"title":"Giới thiệu về dự án"},["/about/project","/about/project.md"]],
  ["v-74bc627b","/about/",{"title":"Giới thiệu về mình"},["/about/index.html","/about/README.md"]],
  ["v-a3c54c30","/dsa/session1.html",{"title":""},["/dsa/session1","/dsa/session1.md"]],
  ["v-a05b9af2","/dsa/session2.html",{"title":""},["/dsa/session2","/dsa/session2.md"]],
  ["v-9cf1e9b4","/dsa/session3.html",{"title":""},["/dsa/session3","/dsa/session3.md"]],
  ["v-6d2014de","/java-oop/",{"title":"Lời nói đầu"},["/java-oop/index.html","/java-oop/readme.md"]],
  ["v-2d29cf6d","/java-oop/session1.html",{"title":"Bài 1. Lập trình hướng đối tượng"},["/java-oop/session1","/java-oop/session1.md"]],
  ["v-2edea80c","/java-oop/session2.html",{"title":"Bài 2. Các tính chất"},["/java-oop/session2","/java-oop/session2.md"]],
  ["v-6c67d393","/github/",{"title":"Lời nói đầu"},["/github/index.html","/github/readme.md"]],
  ["v-6c2644ab","/github/session1.html",{"title":"Bài 1. Setup môi trường"},["/github/session1","/github/session1.md"]],
  ["v-6ddb1d4a","/github/session2.html",{"title":"Bài 2. Đẩy code lên GitHub"},["/github/session2","/github/session2.md"]],
  ["v-6f8ff5e9","/github/session3.html",{"title":"Bài 3 Undo khi gặp một commit sai"},["/github/session3","/github/session3.md"]],
  ["v-7144ce88","/github/session4.html",{"title":"Bài 4 Làm việc nhóm"},["/github/session4","/github/session4.md"]],
  ["v-72f9a727","/github/session5.html",{"title":"Bài 5. Làm việc với nhánh"},["/github/session5","/github/session5.md"]],
  ["v-74ae7fc6","/github/session6.html",{"title":"Bài 6. Thao tác bằng GitHub Desktop"},["/github/session6","/github/session6.md"]],
  ["v-76635865","/github/session7.html",{"title":"Bài 7"},["/github/session7","/github/session7.md"]],
  ["v-78183104","/github/session8.html",{"title":"Bài 8"},["/github/session8","/github/session8.md"]],
  ["v-63e5b0be","/java-core/",{"title":"Lời nói đầu"},["/java-core/index.html","/java-core/readme.md"]],
  ["v-a1cf3540","/java-core/session1.html",{"title":"Bài 1. Giới thiệu về Java"},["/java-core/session1","/java-core/session1.md"]],
  ["v-9e658402","/java-core/session2.html",{"title":"Bài 2. Sử dụng biến, toán tử và các kiểu dữ liệu"},["/java-core/session2","/java-core/session2.md"]],
  ["v-9afbd2c4","/java-core/session3.html",{"title":"Bài 3. Cấu trúc rẽ nhánh"},["/java-core/session3","/java-core/session3.md"]],
  ["v-97922186","/java-core/session4.html",{"title":"Bài 4. Vòng lặp"},["/java-core/session4","/java-core/session4.md"]],
  ["v-94287048","/java-core/session5.html",{"title":"Bài 5. Mảng"},["/java-core/session5","/java-core/session5.md"]],
  ["v-90bebf0a","/java-core/session6.html",{"title":"Bài 6. Chuỗi"},["/java-core/session6","/java-core/session6.md"]],
  ["v-8d550dcc","/java-core/session7.html",{"title":"Bài 7. Phương thức"},["/java-core/session7","/java-core/session7.md"]],
  ["v-89eb5c8e","/java-core/session8.html",{"title":"Tổng kết. Bài tập cuối môn Java căn bản"},["/java-core/session8","/java-core/session8.md"]],
  ["v-2fe4ecaa","/nodejs/",{"title":"Lời nói đầu"},["/nodejs/index.html","/nodejs/readme.md"]],
  ["v-c27994da","/nodejs/session1.html",{"title":"Bài 1. Tìm hiểu về NodeJS"},["/nodejs/session1","/nodejs/session1.md"]],
  ["v-bf0fe39c","/nodejs/session2.html",{"title":"Bài 2. Tìm hiểu về Ejs"},["/nodejs/session2","/nodejs/session2.md"]],
  ["v-bba6325e","/nodejs/session3.html",{"title":"Bài 3. Làm việc với MySql"},["/nodejs/session3","/nodejs/session3.md"]],
  ["v-b83c8120","/nodejs/session4.html",{"title":"Bài 4. Lập trình MVC"},["/nodejs/session4","/nodejs/session4.md"]],
  ["v-b4d2cfe2","/nodejs/session5.html",{"title":"Bài 5. Giới thiệu Restful API"},["/nodejs/session5","/nodejs/session5.md"]],
  ["v-b1691ea4","/nodejs/session6.html",{"title":"Bài 6. Xây dựng Restful API"},["/nodejs/session6","/nodejs/session6.md"]],
  ["v-adff6d66","/nodejs/session7.html",{"title":"Bài 7. Xác thực và xác nhận người dùng"},["/nodejs/session7","/nodejs/session7.md"]],
  ["v-aa95bc28","/nodejs/session8.html",{"title":"Bài 8. Làm việc với MongoDB"},["/nodejs/session8","/nodejs/session8.md"]],
  ["v-f1eb35fc","/php-core/",{"title":"Lời nói đầu"},["/php-core/index.html","/php-core/readme.md"]],
  ["v-91bc80c8","/php-core/session1.html",{"title":"Bài 1. Giới thiệu về PHP"},["/php-core/session1","/php-core/session1.md"]],
  ["v-8e52cf8a","/php-core/session2.html",{"title":"Bài 2. Sử dụng các kiểu dữ liệu"},["/php-core/session2","/php-core/session2.md"]],
  ["v-8ae91e4c","/php-core/session3.html",{"title":"Bài 3. Hàm và HTML"},["/php-core/session3","/php-core/session3.md"]],
  ["v-877f6d0e","/php-core/session4.html",{"title":"Bài 4. Forms"},["/php-core/session4","/php-core/session4.md"]],
  ["v-8415bbd0","/php-core/session5.html",{"title":"Bài 5. File"},["/php-core/session5","/php-core/session5.md"]],
  ["v-80ac0a92","/php-core/session6.html",{"title":"Bài 6. MySQLi căn bản"},["/php-core/session6","/php-core/session6.md"]],
  ["v-7d425954","/php-core/session7.html",{"title":"Bài 7. MySQLi nâng cao"},["/php-core/session7","/php-core/session7.md"]],
  ["v-79d8a816","/php-core/session8.html",{"title":"Bài 8. Session, Cookie và PDO"},["/php-core/session8","/php-core/session8.md"]],
  ["v-2f9253b4","/sql-server/",{"title":"Lời nói đầu"},["/sql-server/index.html","/sql-server/readme.md"]],
  ["v-c0ba7bac","/sql-server/session1.html",{"title":"Tổng quan về hệ QT-CSDL"},["/sql-server/session1","/sql-server/session1.md"]],
  ["v-bd50ca6e","/sql-server/session2.html",{"title":"Tạo CSDL quan hệ và T-SQL"},["/sql-server/session2","/sql-server/session2.md"]],
  ["v-b9e71930","/sql-server/session3.html",{"title":"Các hàm hệ thống và xử lý chuỗi"},["/sql-server/session3","/sql-server/session3.md"]],
  ["v-b67d67f2","/sql-server/session4.html",{"title":"Điều kiện và vòng lặp"},["/sql-server/session4","/sql-server/session4.md"]],
  ["v-b313b6b4","/sql-server/session5.html",{"title":"Stored Procedures"},["/sql-server/session5","/sql-server/session5.md"]],
  ["v-afaa0576","/sql-server/session6.html",{"title":"Trigger"},["/sql-server/session6","/sql-server/session6.md"]],
  ["v-ac405438","/sql-server/session7.html",{"title":"Function và View"},["/sql-server/session7","/sql-server/session7.md"]],
  ["v-a8d6a2fa","/sql-server/session8.html",{"title":"Sao lưu và phục hồi CSDL"},["/sql-server/session8","/sql-server/session8.md"]],
  ["v-15551100","/tech/",{"title":"Links"},["/tech/index.html","/tech/README.md"]],
  ["v-77e2f3a3","/post/backend/session-cookie/",{"title":"Tìm hiểu về Session, Cookie trong Xác thực người dùng","subtitle":"Session, Cookie là gì?","date":"2023-09-03T00:00:00.000Z","tags":["Backend","Authentication","Authoriztion"],"headerImage":"https://github.com/dangtranhuu/images/blob/main/angurvad/backend/session-cookie/bn.png?raw=true","excerpt":"<p>Trong mô hình <a href=\"\">CSR</a> hay Client-Side-Rendering việc lưu thông tin người dùng thường được xác định thông qua giá trị của Session...</p>\n"},["/post/backend/session-cookie/index.html","/posts/backend/session-cookie.html","/posts/backend/session-cookie.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-15534fdd","/tags/",{"title":"Tags"},["/tags/index.html"]],
  ["v-8daa1a0e","/",{"title":"Home"},["/index.html"]],
  ["v-a3ca2210","/tags/backend/",{"title":"Backend | Tags"},["/tags/backend/index.html"]],
  ["v-1405c73a","/tags/authentication/",{"title":"Authentication | Tags"},["/tags/authentication/index.html"]],
  ["v-f4a6573c","/tags/authoriztion/",{"title":"Authoriztion | Tags"},["/tags/authoriztion/index.html"]],
  ["v-3a1f8885","/page/1/",{"title":"Home"},["/page/1/index.html"]],
]
