export const pagesRoutes = [
  ["v-31767f5b","/about/project.html",{"title":"Giới thiệu về dự án"},["/about/project","/about/project.md"]],
  ["v-74bc627b","/about/",{"title":"Giới thiệu về mình"},["/about/index.html","/about/README.md"]],
  ["v-6c67d393","/github/",{"title":"Lời nói đầu"},["/github/index.html","/github/readme.md"]],
  ["v-6c2644ab","/github/session1.html",{"title":"Bài 1. Setup môi trường"},["/github/session1","/github/session1.md"]],
  ["v-6ddb1d4a","/github/session2.html",{"title":"Bài 2. Đẩy code lên GitHub"},["/github/session2","/github/session2.md"]],
  ["v-6f8ff5e9","/github/session3.html",{"title":"Bài 3"},["/github/session3","/github/session3.md"]],
  ["v-7144ce88","/github/session4.html",{"title":"Bài 4"},["/github/session4","/github/session4.md"]],
  ["v-72f9a727","/github/session5.html",{"title":"Bài 5"},["/github/session5","/github/session5.md"]],
  ["v-74ae7fc6","/github/session6.html",{"title":"Bài 6"},["/github/session6","/github/session6.md"]],
  ["v-76635865","/github/session7.html",{"title":"Bài 7"},["/github/session7","/github/session7.md"]],
  ["v-78183104","/github/session8.html",{"title":"Bài 8"},["/github/session8","/github/session8.md"]],
  ["v-5663e3fd","/ebook/dsa/session1/",{"title":"Giới thiệu về cấu trúc dữ liệu và giải thuật","subtitle":"Cấu trúc dữ liệu và giải thuật","date":"2023-06-21T00:00:00.000Z","tags":["Data structures","Algorithms","DSA"],"headerImage":"https://github.com/dangtranhuu/images/blob/main/angurvad/dsa/session1/banner.png?raw=true","excerpt":"<p>Cấu trúc dữ liệu và giải thuật là cụm từ đáng sợ nhất của những sinh viên chưa biết tới website này khi học lập trình.</p>\n"},["/ebook/dsa/session1/index.html","/dsa/session1.html","/dsa/session1.md"]],
  ["v-5663e41c","/ebook/dsa/session2/",{"title":"Cấu trúc danh sách đặc","subtitle":"Cấu trúc dữ liệu và giải thuật","date":"2023-06-11T00:00:00.000Z","tags":["Data structures","DSA"],"headerImage":"https://github.com/dangtranhuu/images/blob/main/angurvad/dsa/session2/banner.png?raw=true","excerpt":"<p>Danh sách đặc là cấu trúc bạn gặp phải rất nhiều, nhưng có lẽ bạn sẽ không biết nếu chưa học về DSA.</p>\n"},["/ebook/dsa/session2/index.html","/dsa/session2.html","/dsa/session2.md"]],
  ["v-5663e43b","/ebook/dsa/session3/",{"title":"Danh sách liên kết","subtitle":"Cấu trúc dữ liệu và giải thuật","date":"2023-06-11T00:00:00.000Z","tags":["Data structures","DSA"],"headerImage":"https://github.com/dangtranhuu/images/blob/main/angurvad/dsa/session3/banner.png?raw=true","excerpt":"<p>Danh sách đặc là cấu trúc bạn gặp phải rất nhiều, nhưng có lẽ bạn sẽ không biết nếu chưa học về DSA.</p>\n"},["/ebook/dsa/session3/index.html","/dsa/session3.html","/dsa/session3.md"]],
  ["v-2fe4ecaa","/nodejs/",{"title":"Lời nói đầu"},["/nodejs/index.html","/nodejs/readme.md"]],
  ["v-c27994da","/nodejs/session1.html",{"title":"Bài 1. Tìm hiểu về NodeJS"},["/nodejs/session1","/nodejs/session1.md"]],
  ["v-bf0fe39c","/nodejs/session2.html",{"title":"Bài 2. Tìm hiểu về Ejs"},["/nodejs/session2","/nodejs/session2.md"]],
  ["v-bba6325e","/nodejs/session3.html",{"title":"Bài 3. Làm việc với MySql"},["/nodejs/session3","/nodejs/session3.md"]],
  ["v-b83c8120","/nodejs/session4.html",{"title":"Bài 4. Lập trình MVC"},["/nodejs/session4","/nodejs/session4.md"]],
  ["v-b4d2cfe2","/nodejs/session5.html",{"title":"Bài 5. Giới thiệu Restful API"},["/nodejs/session5","/nodejs/session5.md"]],
  ["v-b1691ea4","/nodejs/session6.html",{"title":"Bài 6. Xây dựng Restful API"},["/nodejs/session6","/nodejs/session6.md"]],
  ["v-adff6d66","/nodejs/session7.html",{"title":"Bài 7. Xác thực và xác nhận người dùng"},["/nodejs/session7","/nodejs/session7.md"]],
  ["v-aa95bc28","/nodejs/session8.html",{"title":"Bài 8. Làm việc với MongoDB"},["/nodejs/session8","/nodejs/session8.md"]],
  ["v-63e5b0be","/java-core/",{"title":"Lời nói đầu"},["/java-core/index.html","/java-core/readme.md"]],
  ["v-a1cf3540","/java-core/session1.html",{"title":"Bài 1. Giới thiệu về Java"},["/java-core/session1","/java-core/session1.md"]],
  ["v-9e658402","/java-core/session2.html",{"title":"Bài 2. Sử dụng biến, toán tử và các kiểu dữ liệu"},["/java-core/session2","/java-core/session2.md"]],
  ["v-9afbd2c4","/java-core/session3.html",{"title":"Bài 3. Cấu trúc rẽ nhánh"},["/java-core/session3","/java-core/session3.md"]],
  ["v-97922186","/java-core/session4.html",{"title":"Bài 4. Vòng lặp"},["/java-core/session4","/java-core/session4.md"]],
  ["v-94287048","/java-core/session5.html",{"title":"Bài 5. Mảng"},["/java-core/session5","/java-core/session5.md"]],
  ["v-90bebf0a","/java-core/session6.html",{"title":"Bài 6. Chuỗi"},["/java-core/session6","/java-core/session6.md"]],
  ["v-8d550dcc","/java-core/session7.html",{"title":"Bài 7. Phương thức"},["/java-core/session7","/java-core/session7.md"]],
  ["v-89eb5c8e","/java-core/session8.html",{"title":"Tổng kết. Bài tập cuối môn Java căn bản"},["/java-core/session8","/java-core/session8.md"]],
  ["v-6d2014de","/java-oop/",{"title":"Lời nói đầu"},["/java-oop/index.html","/java-oop/readme.md"]],
  ["v-2d29cf6d","/java-oop/session1.html",{"title":"Bài 1. Lập trình hướng đối tượng"},["/java-oop/session1","/java-oop/session1.md"]],
  ["v-2edea80c","/java-oop/session2.html",{"title":"Bài 2. Các tính chất"},["/java-oop/session2","/java-oop/session2.md"]],
  ["v-66a4fd02","/post/2022/01/29/about-me/",{"title":"Tìm hiểu về mình","subtitle":"Mình là ai?","date":"2022-01-29T00:00:00.000Z","tags":["Giới thiệu"],"headerImage":"/img/in-post/2022-01-29/header.jpeg","excerpt":"<p>Rất vui vì nếu bạn có tìm hiểu về dự án, rất mong đồng hành cùng bạn trong suốt quá trình học tập về công nghệ sắp tới nhé ^^</p>\n"},["/post/2022/01/29/about-me/index.html","/posts/2022-01-29-about-me.html","/posts/2022-01-29-about-me.md"]],
  ["v-0df3c318","/post/2022/02/21/about-project/",{"title":"Giới thiệu về dự án","subtitle":"Cùng mình tìm hiểu về dự án nhé ^^","date":"2022-02-21T00:00:00.000Z","tags":["Giới thiệu"],"headerImage":"/img/in-post/2018-09-01/header.jpeg","excerpt":"<p>Dự án được phát triển với mục đích chia sẽ những kiến thức mình có được, sẽ không nhiều đâu nhưng mình rất vui nếu nó phù hợp và có ích với bạn.</p>\n"},["/post/2022/02/21/about-project/index.html","/posts/2022-02-21-about-project.html","/posts/2022-02-21-about-project.md"]],
  ["v-15551100","/tech/",{"title":"Links"},["/tech/index.html","/tech/README.md"]],
  ["v-77e2f3a3","/post/backend/session-cookie/",{"title":"Tìm hiểu về Session, Cookie trong Xác thực người dùng","subtitle":"Session, Cookie là gì?","date":"2023-09-03T00:00:00.000Z","tags":["Backend","Authentication","Authoriztion"],"headerImage":"https://github.com/dangtranhuu/images/blob/main/angurvad/backend/session-cookie/bn.png?raw=true","excerpt":"<p>Trong mô hình <a href=\"\">CSR</a> hay Client-Side-Rendering việc lưu thông tin người dùng thường được xác định thông qua giá trị của Session...</p>\n"},["/post/backend/session-cookie/index.html","/posts/backend/session-cookie.html","/posts/backend/session-cookie.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-15534fdd","/tags/",{"title":"Tags"},["/tags/index.html"]],
  ["v-8daa1a0e","/",{"title":"Home"},["/index.html"]],
  ["v-a20319ee","/tags/data-structures/",{"title":"Data structures | Tags"},["/tags/data-structures/index.html"]],
  ["v-534676ce","/tags/algorithms/",{"title":"Algorithms | Tags"},["/tags/algorithms/index.html"]],
  ["v-cd256bcc","/tags/dsa/",{"title":"DSA | Tags"},["/tags/dsa/index.html"]],
  ["v-3dadba58","/tags/gi%E1%BB%9Bi-thi%E1%BB%87u/",{"title":"Giới thiệu | Tags"},["/tags/giới-thiệu/","/tags/gi%E1%BB%9Bi-thi%E1%BB%87u/index.html"]],
  ["v-a3ca2210","/tags/backend/",{"title":"Backend | Tags"},["/tags/backend/index.html"]],
  ["v-1405c73a","/tags/authentication/",{"title":"Authentication | Tags"},["/tags/authentication/index.html"]],
  ["v-f4a6573c","/tags/authoriztion/",{"title":"Authoriztion | Tags"},["/tags/authoriztion/index.html"]],
  ["v-3a1f8885","/page/1/",{"title":"Home"},["/page/1/index.html"]],
]
