export const data = JSON.parse("{\"key\":\"v-336bc054\",\"path\":\"/ebook/java-core/session2/\",\"title\":\"Bài 2. Sử dụng biến, toán tử và các kiểu dữ liệu trong Java\",\"lang\":\"en-US\",\"frontmatter\":{\"layout\":\"Post\",\"title\":\"Bài 2. Sử dụng biến, toán tử và các kiểu dữ liệu trong Java\",\"subtitle\":\"Lập trình Java căn bản\",\"author\":\"Theanishtar\",\"date\":\"2023-06-03T00:00:00.000Z\",\"useHeaderImage\":true,\"headerImage\":\"https://github.com/dangtranhuu/images/blob/main/angurvad/java-core/session2/banner.png?raw=true\",\"headerMask\":\"rgba(39, 62, 77, 0.61)\",\"permalinkPattern\":\"/ebook/java-core/:slug/\",\"tags\":[\"Java Core\"]},\"excerpt\":\"<p>Biến là đối tượng cơ bản nhất trong lập trình, dùng để lưu giá trị. Vậy biến trong Java là gì ta 🤔</p>\\n\",\"headers\":[{\"level\":2,\"title\":\"1. Các kiểu dữ liệu nguyên thủy\",\"slug\":\"_1-cac-kieu-du-lieu-nguyen-thuy\",\"children\":[{\"level\":3,\"title\":\"Tổng hợp các kiểu dữ liệu nguyên thủy trong Java\",\"slug\":\"tong-hop-cac-kieu-du-lieu-nguyen-thuy-trong-java\",\"children\":[{\"level\":4,\"title\":\"Nên sử dụng số thực là float hay double :\",\"slug\":\"nen-su-dung-so-thuc-la-float-hay-double\",\"children\":[]}]}]},{\"level\":2,\"title\":\"2. Kiểu dữ liệu không nguyên thuỷ\",\"slug\":\"_2-kieu-du-lieu-khong-nguyen-thuy\",\"children\":[]},{\"level\":2,\"title\":\"3. Biến\",\"slug\":\"_3-bien\",\"children\":[{\"level\":3,\"title\":\"Khởi tạo biến\",\"slug\":\"khoi-tao-bien\",\"children\":[]},{\"level\":3,\"title\":\"Quy tắc đặt biến\",\"slug\":\"quy-tac-đat-bien\",\"children\":[]},{\"level\":3,\"title\":\"Hiển thị biến\",\"slug\":\"hien-thi-bien\",\"children\":[]}]},{\"level\":2,\"title\":\"4. Toán tử\",\"slug\":\"_4-toan-tu\",\"children\":[{\"level\":3,\"title\":\"Toán tử số học (Arithmetic)\",\"slug\":\"toan-tu-so-hoc-arithmetic\",\"children\":[]},{\"level\":3,\"title\":\"Toán tử gán (Assignment)\",\"slug\":\"toan-tu-gan-assignment\",\"children\":[]},{\"level\":3,\"title\":\"Toán tử so sánh (Comparision)\",\"slug\":\"toan-tu-so-sanh-comparision\",\"children\":[]},{\"level\":3,\"title\":\"Toán tử logic (Logical)\",\"slug\":\"toan-tu-logic-logical\",\"children\":[]},{\"level\":3,\"title\":\"Toán tử Bit (Bitwise)\",\"slug\":\"toan-tu-bit-bitwise\",\"children\":[]}]},{\"level\":2,\"title\":\"5. Bài tập\",\"slug\":\"_5-bai-tap\",\"children\":[{\"level\":3,\"title\":\"Tính lãi xuất kép trong\",\"slug\":\"tinh-lai-xuat-kep-trong\",\"children\":[]}]}],\"readingTime\":{\"minutes\":17,\"words\":2630},\"filePathRelative\":\"posts/java-core/session2.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
