import { defineClientConfig } from "@vuepress/client";
import { addIcons } from "oh-vue-icons";
import {
	FaFortAwesome,
	FaSatelliteDish,
	FaTag,
	OiRocket,
	RiLinkM,
	RiGithubFill,
	RiLinkedinBoxFill,
	RiFacebookBoxFill,
	RiTwitterFill,
	RiZhihuLine,
	HiMail,
	FaPaw,
	AiCv,
	AiGoogleScholarSquare,
	ViFileTypeJar,
	ViFileTypeJsp,
	CoSpring,
	RiCodeSSlashLine,
	ViFileTypeCpp,
	ViFileTypeJs,
	SiAwslambda,
	ViFileTypeLightJsmap,
	LaToolsSolid,
	ViFileTypeGit,
	GiEvilBook,
	GiPc,
	SiCodersrank,
	FcCommandLine,
	PxMonitor,
	ViFileTypeNode,
	BiFiletypeJava
} from "oh-vue-icons/icons";

addIcons(
	FaFortAwesome,
	FaSatelliteDish,
	FaTag,
	OiRocket,
	RiLinkM,
	RiGithubFill,
	RiLinkedinBoxFill,
	RiFacebookBoxFill,
	RiTwitterFill,
	RiZhihuLine,
	HiMail,
	FaPaw,
	AiCv,
	AiGoogleScholarSquare,
	ViFileTypeJar,
	ViFileTypeJsp,
	CoSpring,
	RiCodeSSlashLine,
	ViFileTypeCpp,
	ViFileTypeJs,
	SiAwslambda,
	ViFileTypeLightJsmap,
	LaToolsSolid,
	ViFileTypeGit,
	GiEvilBook,
	GiPc,
	SiCodersrank,
	FcCommandLine,
	PxMonitor,
	ViFileTypeNode,
	ViFileTypeJar,
	BiFiletypeJava
);

export default defineClientConfig({});
